### ISSUE TITLE
2 dorks require a search operator

### ISSUE THREAD

**Issue by carnal0wnage** [techgaun/github-dorks#33]
The following github dorks require a search operator and fail

extension:avastlic | Contains license keys for Avast! Antivirus
-- | --
extension:dbeaver-data-sources.xml | DBeaver config containing MySQL Credentials

**Comment by techgaun** [comment]
@carnal0wnage thanks for opening the issue. Could you help me understand more when you say _require a search operator and fail_

**Comment by Plazmaz** [comment]
I think this is due to restrictions on github search that require text to be used with filters. For instance, this is the result of one of the queries:
![image](https://user-images.githubusercontent.com/1331014/57587218-66424600-74b6-11e9-94ae-8d4b0217a4ea.png)
This one's probably my bad, as a few of my contributions were created for a tool I wrote that parsed github dorks, not necessarily the github search API. The fix is going to be adding text in the files.
```
extension:avastlic "support.avast.com"
filename:dbeaver-data-sources extension:.xml xml
```

**Comment by techgaun** [comment]
ahh I see thanks @Plazmaz 
/cc @carnal0wnage
