### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by danielmiessler** [techgaun/github-dorks#5]
Any ideas for avoiding the 403 errors? Still getting them on basic queries, even when using authentication.

**Comment by techgaun** [comment]
@danielmiessler that's basically happening because github search rate limit is too low([Reference](https://developer.github.com/v3/search/#rate-limit)). Its 30 per minute. A periodic sleep timeout or handling the error(by waiting for current minute) and re-running the iteration might help. I still need to gather time to handle this. I did update it locally but haven't really been able to test it well. Will see on the upcoming weekend.

**Comment by techgaun** [comment]
This should be better now. The tool now waits for api rate limit to be reset and then retries the dork again.

**Comment by sigmavirus24** [comment]
FYI, the rate limit is 30 requests per hour, not per minute. The requests that count against that are:

- The initial search request
- Using pagination to find all potential results returned by GitHub (so each page counts against the limit)

**Comment by techgaun** [comment]
@sigmavirus24 thanks! I am slightly confused here.
Below is what is listed at https://developer.github.com/v3/search/#rate-limit
> The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

But since you've been doing github api for such long time, can you clarify if that's practical limit. The tool works fine at the moment for now (probably it skips one search) but I feel I am able to do much more than 30 requests per hour.

**Comment by sigmavirus24** [comment]
Ah, they've changed that since the last time I saw it. It used to be 30 unauthenticated requests per hour and 60 authenticated requests per hour.

What you have in 0c49019 looks correct to me.

**Comment by techgaun** [comment]
ahh okay thanks for checking that @sigmavirus24
